sudo: required
dist: trusty
language: node_js
node_js: 9
branches:
  only:
  - master
  - develop
deploy:
  provider: heroku
  app:
    master: donuts
    develop: donuts-dev
  skip_cleanup: true
  api_key:
    secure: LItXa4lRwKrFQvOWINUY8iyHHcTtqr+SzAb7wNt1BaoYct1d7WaGIocNwqTZC+ByH9qfSEfu9ccHPGdy1blkfCT8qPDA5JYcjj3qyIY9wtGJm5iXuzwpHraMyCZ9hzn//pKfEoGtb75WsciFMGn6FuPh1dHAkl+8Nn4f7BwiPVx9/gXBVT7XXH5k4dRS4bZ9srrrB/dsD1SGNjtWrPKqMoamnvsxCAoADuFeanHQldhHUAGOPpnX1U7Nar2ZpZyIyhDP08MxVq6UYVlikSkOYbWwgJnPHHYr8G2JozeSnf/Aa5lTo57ORCSmbdkA1LlctPetCF7CMks0/RqjfmAB+WNmgK/GwGlWWloR3bFIiCCYsg++5UkfqS86oeiikjDhr/0MuODsZ9XpIfX6qOvwfGkdk4Gcz9WMRF4ldIrFHuw1Q4qT08daIrg1phY4YESE/pA9yi9kmXh3bIGAy8xGIyN3RLJQJQhOnw0j/RnpTLZA4D4TNqoURq9lHJLLE+KZs7QaUVXTUifnh8jIK1DaG+3MOk0r+n+UD3I4ANihUZ4kbxUqC59iHOVbCkxEjDt0RvBbBTR88yl1lYaPd1MPipUQHmyAAmt8imQnhOHJpvFqEV+JaT7UF33EgYW5SN6AlROzXBOW0oR+NIeOdR1W1wo1N+6KX5hlHHDXsS8uOZI=
