sudo: required
dist: trusty
language: node_js
node_js: 9
branches:
  only:
  - master
  - develop
deploy:
  provider: heroku
  app:
    master: donuts
    develop: donuts-dev
    yury: donutswars
  skip_cleanup: true
  api_key:
    secure: e9QJu9pboaDhcG9hM6sKN8nFv1l0bjku81y+UA2dwJ/b7Z//mOngjPLTwyh6pnPmI1PYiTdC5unYEN/IxlsuF+VsK2XfynJfv58/8OAqYF4ICaqYip2rMBdlQZbOFLo2MvIU5j0Cp6ZeROOgva2vsRIJSiJxKVHMDTIScGX3WK1j96W9OwdSuxTuyH0Lkd0DwTGyVN9Tpv2KbOuuv7XUq00WVkg9VYvmX58d+XF0vEhddIzZj3ZrFnRCV1p/PQKu1cUsEJ1tolbMUWYcqMVa3f7pAeClphbRKn0ic7F/0afh2WnV5w5RpzNbqnB+fEKN7tyR467GAkp+WNNliFFLVpOhnQ0AWhSxsceC+XJD2NE2npemg+wmO0QQOviVBnmu8iCS2ScgHLgOZ3tq5uwea1ZtLXdG+N5HVUQ2kNf/96Wb82ZwF0KkEfcpKCm0SyzpBoEKnaOhhFPmy04aJshVhbNIEgcLF0YkczjxaqHdmrtDzBj5RKtfScmLNgkECAZc1LZ8NAhqqqIYISW2n3QtBDMeeZb57oVaB2YunmllT8X9dL6npVGyQ0TgYH+Ig9RMi8lu9jv1DjsqhOYVcAd5Yaml7NMAhfrGCA0EYwsjejuAiCR/xft4zDgkblJ8UXXzionkXfhOFUiAy+ZYLvlbw6nbQyK0arLLy6ZCldgxU94=
