language: node_js
node_js:
- '8'
script:
- eval "$(ssh-agent -s)"
- ssh-keyscan -H 78.155.207.152 >> ~/.ssh/known_hosts
- chmod 600 $HOME/.ssh/id_rsa
- ssh deploy@78.155.207.152 'rm -rf /var/www/*'
- scp -r ./src/* deploy@78.155.207.152:/var/www
before_install:
- openssl aes-256-cbc -K $encrypted_34838692b38c_key -iv $encrypted_34838692b38c_iv
  -in id_rsa_vscale_deploy.enc -out ~/.ssh/id_rsa -d
