export const events = {
  GAME: {
    START: 'START',
    STATE_CHANGED: 'STATE_CHANGED',
    FINISH: 'FINISH',
    MISSED: 'MISSED',
    COLLISION: 'COLLISION',
    LAUNCH_DONUT: 'LAUNCH_DONUT',
    POSITION_CHANGED: 'POSITION_CHANGED',
  },

  START_GAME: {
    LEVEL_SELECTED: 'SELECTED',
    SINGLE_CLICKED: 'SINGLE',
    BATTLE_CLICKED: 'BATTLE',
  },

  CONTROL: {
    PRESSED: 'PRESSED',
    CLICKED: 'ON_CANVAS_CLICKED',
    MOUSE_MOVED: 'MOUSE_MOVED',
  },

  AUTH: {
    GET_USER: 'GET_USER',
    USER: 'USER',
  },

  WS: {
    MESSAGE: 'MSG',
    START_GAME: 'START_MULTIPLAYER',
  },

  ROUTE: {
    SIGN_UP: 'SIGN_UP',
    LOGIN: 'LOGIN',
    LOGOUT: 'LOGOUT',
    PROFILE: 'PROFILE',
    HELP: 'HELP',
  }
};
