export const events = {
  GAME: {
    START: 'START',
    STATE_CHANGED: 'STATE_CHANGED',
    FINISH: 'FINISH',
    ON_BOTTOM: 'ON_BOTTOM',
    COLLISION: 'COLLISION',
    LAUNCH_DONUT: 'LAUNCH_DONUT',
    POSITION_CHANGED: 'POSITION_CHANGED',
  },

  CONTROL: {
    PRESSED: 'PRESSED',
    CLICKED: 'ON_CANVAS_CLICKED',
    MOUSE_MOVED: 'MOUSE_MOVED',
  },
  AUTH: {
    SIGN_UP: 'SIGN_UP',
    LOGIN: 'LOGIN',
    LOGOUT: 'LOGOUT',
  }
};
