export const events = {
  GAME: {
    START: 'START',
    STATE_CHANGED: 'STATE_CHANGED',
    FINISH: 'FINISH',
    ON_BOTTOM: 'ON_BOTTOM',
    LAUNCH_DONUT: 'LAUNCH_DONUT',
  },

  CONTROL: {
    PRESSED: 'PRESSED',
    CLICKED: 'ON_CANVAS_CLICKED',
  }
};
